### ISSUE TITLE
Relocate fanal into Trivy

### ISSUE THREAD

**Issue by liamg** [aquasecurity/trivy#2277]
## Tasks

- [x] Put fanal/ dir into pkg/
- [x] Remove unnecessary files such as README.md, cmd/fanal etc.
- [x] Fix import paths from github.com/aquasecurity/fanal with github.com/aquasecurity/trivy/pkg/fanal/
- [x] Retain integration tests

## Tasks once this is ready to merge

- [ ] Update README.md in fanal like "Moved this project to github.com/aquasecurity/trivy"
- [ ] Archive fanal (do not remove repo)

_Note: Teppei will move some packages to trivy/pkg/* later, e.g. pkg/fanal/artifact to pkg/artifact_

This looks useful: https://alexharv074.github.io/puppet/2017/10/04/merge-a-git-repository-and-its-history-into-a-subdirectory-of-a-second-git-repository.html - thank you @alexharv074!
