### ISSUE TITLE
Speed up ebs scanning

### ISSUE THREAD

**Issue by masahiro331** [aquasecurity/trivy#3350]
EBS Scan calls EBS API and fetches the EBS blocks in a single thread.
To parallelize the fetch for ebs blocks, trivy needs to thread-safe parse in the filesystem and virtual disk.

### Tasks
- [ ] Thread-safe parse in xfs
- [ ] Thread-safe parse in ext4
- [ ] Thread-safe parse in vmdk
- [ ] Thread-safe parse in MBR, GPT
- [ ] Thread-safe read in EBS
