### ISSUE TITLE
feat(python): Add support for astral UV

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#7653]
## Description
Parse [uv.lock](https://docs.astral.sh/uv/concepts/projects/#configuring-the-project-environment-path) to identify dependencies ([example](https://github.com/astral-sh/uv/blob/312eeb8f573d36f6df658f85ecadc52799647bb3/scripts/benchmark/uv.lock)).

## TODO
- [x] Add new [parser](https://github.com/aquasecurity/trivy/tree/4926da79de901fba73819d71845ec0355b68ae0f/pkg/dependency/parser/python).
   - [ ] `uv.lock` contains dependencies for package - so parser should detect `[]Package` and `[]Dependency`.(check the case when 2 packages with different versions are used (if possible)
   - [ ] `uv.lock` contains root package (e.g. https://github.com/astral-sh/uv/blob/312eeb8f573d36f6df658f85ecadc52799647bb3/scripts/benchmark/uv.lock#L27). Can we detect that this is root package (e.g. from `source` field)?
   - [x] fill Relationship field.
- [x] add new [analyzer](https://github.com/aquasecurity/trivy/tree/4926da79de901fba73819d71845ec0355b68ae0f/pkg/fanal/analyzer/language/python). 
   - [ ] If we can detect Root package from `uv.lock` file - we can use [analyzer interface](https://github.com/aquasecurity/trivy/blob/4926da79de901fba73819d71845ec0355b68ae0f/pkg/fanal/analyzer/analyzer.go#L72-L77). If no - we need to use [PostAnalyzer](https://github.com/aquasecurity/trivy/blob/4926da79de901fba73819d71845ec0355b68ae0f/pkg/fanal/analyzer/analyzer.go#L79-L84) and detect root package from `pyproject.toml` file.
   - [ ] This is lock file, so we need to add  it into [TypeLockfiles](https://github.com/aquasecurity/trivy/blob/4926da79de901fba73819d71845ec0355b68ae0f/pkg/fanal/analyzer/const.go#L207) (don't forget about `TypeLanguages`)
- [x] add new type into [purl package](https://github.com/aquasecurity/trivy/blob/4926da79de901fba73819d71845ec0355b68ae0f/pkg/purl/purl.go) 
- [x] update driver for [Python](https://github.com/aquasecurity/trivy/blob/4926da79de901fba73819d71845ec0355b68ae0f/pkg/detector/library/driver.go#L51)
- [x] add unit and integration tests
- [x] docs: update [Python](https://trivy.dev/latest/docs/coverage/language/python/) and [overview](https://trivy.dev/latest/docs/coverage/language/python/) pages

**Comment by knqyf263** [comment]
I assigned it to @nikpivkin since he has time now, but @DmitriyLewen, please help him as you have more knowledge regarding lockfile analysis.

**Comment by knqyf263** [comment]
There are several things to do, like dependency tree, etc. @DmitriyLewen Can you make a list for him first?

**Comment by DmitriyLewen** [comment]
@knqyf263 @nikpivkin I added a TODO list to the issue description.
I'll update it if I remember anything else

**Comment by nikpivkin** [comment]
@DmitriyLewen Thanks!

**Comment by nikpivkin** [comment]
There is a concept of workspaces in uv. In the current PR I didn't add support for workspaces, but I still implemented the analyzer as a `PostAnalyzer` so that we can make fewer changes in the future.

**Comment by Aweptimum** [comment]
Was the documentation ever updated to reflect this? It's currently missing from the live site

**Comment by nikpivkin** [comment]
Hi @Aweptimum . v59.0 has not been released yet.
